export const nbaTeamsData = [
	{
		teamId: '1',
		allStar: '0',
		city: 'Atlanta',
		fullName: 'Atlanta Hawks',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/e/ee/Hawks_2016.png',
		nbaFranchise: '1',
		nickname: 'Hawks',
		shortName: 'ATL',
		standings: [
			{
				win: 16,
				loss: 19,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 12,
					win: 10,
					loss: 12,
				},
				division: {
					name: 'southeast',
					rank: 4,
					win: 4,
					loss: 3,
					GamesBehind: 6.5,
				},
				winPercentage: 0.457,
			},
			// {
			// 	win: 41,
			// 	loss: 31,
			// 	seasonYear: 2020,
			// 	conference: {
			// 		name: 'east',
			// 		rank: 5,
			// 		win: 24,
			// 		loss: 18,
			// 	},
			// 	division: {
			// 		name: 'southeast',
			// 		rank: 1,
			// 		win: 9,
			// 		loss: 3,
			// 		GamesBehind: 0.0,
			// 	},
			// 	winPercentage: 0.569,
			// },
		],
	},
	{
		teamId: '2',
		allStar: '0',
		city: 'Boston',
		fullName: 'Boston Celtics',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/6/65/Celtics_de_Boston_logo.svg/1024px-Celtics_de_Boston_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Celtics',
		shortName: 'BOS',
		standings: [
			{
				win: 17,
				loss: 19,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 9,
					win: 11,
					loss: 10,
				},
				division: {
					name: 'atlantic',
					rank: 3,
					win: 4,
					loss: 4,
					GamesBehind: 7.5,
				},
				winPercentage: 0.472,
			},
			// {
			// 	win: 36,
			// 	loss: 36,
			// 	seasonYear: 2020,
			// 	conference: {
			// 		name: 'east',
			// 		rank: 7,
			// 		win: 20,
			// 		loss: 22,
			// 	},
			// 	division: {
			// 		name: 'atlantic',
			// 		rank: 4,
			// 		win: 4,
			// 		loss: 8,
			// 		GamesBehind: 13.0,
			// 	},
			// 	winPercentage: 0.5,
			// },
		],
	},
	{
		teamId: '4',
		allStar: '0',
		city: 'Brooklyn',
		fullName: 'Brooklyn Nets',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Brooklyn_Nets_newlogo.svg/130px-Brooklyn_Nets_newlogo.svg.png',
		nbaFranchise: '1',
		nickname: 'Nets',
		shortName: 'BKN',
		standings: [
			{
				win: 23,
				loss: 10,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 2,
					win: 17,
					loss: 7,
				},
				division: {
					name: 'atlantic',
					rank: 1,
					win: 6,
					loss: 1,
					GamesBehind: 0.0,
				},
				winPercentage: 0.697,
			},
			{
				win: 48,
				loss: 24,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 2,
					win: 26,
					loss: 16,
				},
				division: {
					name: 'atlantic',
					rank: 2,
					win: 8,
					loss: 4,
					GamesBehind: 1.0,
				},
				winPercentage: 0.667,
			},
		],
	},
	{
		teamId: '5',
		allStar: '0',
		city: 'Charlotte',
		fullName: 'Charlotte Hornets',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/f/f3/Hornets_de_Charlotte_logo.svg/1200px-Hornets_de_Charlotte_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Hornets',
		shortName: 'CHA',
		standings: [
			{
				win: 19,
				loss: 17,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 7,
					win: 11,
					loss: 8,
				},
				division: {
					name: 'southeast',
					rank: 2,
					win: 5,
					loss: 2,
					GamesBehind: 4.0,
				},
				winPercentage: 0.528,
			},
			{
				win: 33,
				loss: 39,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 10,
					win: 20,
					loss: 22,
				},
				division: {
					name: 'southeast',
					rank: 4,
					win: 8,
					loss: 4,
					GamesBehind: 8.0,
				},
				winPercentage: 0.458,
			},
		],
	},
	{
		teamId: '6',
		allStar: '0',
		city: 'Chicago',
		fullName: 'Chicago Bulls',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/d/d1/Bulls_de_Chicago_logo.svg/1200px-Bulls_de_Chicago_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Bulls',
		shortName: 'CHI',
		standings: [
			{
				win: 23,
				loss: 10,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 1,
					win: 14,
					loss: 7,
				},
				division: {
					name: 'central',
					rank: 1,
					win: 4,
					loss: 2,
					GamesBehind: 0.0,
				},
				winPercentage: 0.697,
			},
			{
				win: 31,
				loss: 41,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 11,
					win: 21,
					loss: 21,
				},
				division: {
					name: 'central',
					rank: 3,
					win: 7,
					loss: 5,
					GamesBehind: 15.0,
				},
				winPercentage: 0.431,
			},
		],
	},
	{
		teamId: '7',
		allStar: '0',
		city: 'Cleveland',
		fullName: 'Cleveland Cavaliers',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/0/06/Cavs_de_Cleveland_logo_2017.png/150px-Cavs_de_Cleveland_logo_2017.png',
		nbaFranchise: '1',
		nickname: 'Cavaliers',
		shortName: 'CLE',
		standings: [
			{
				win: 20,
				loss: 16,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 5,
					win: 13,
					loss: 9,
				},
				division: {
					name: 'central',
					rank: 3,
					win: 3,
					loss: 1,
					GamesBehind: 4.5,
				},
				winPercentage: 0.556,
			},
			{
				win: 22,
				loss: 50,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 13,
					win: 16,
					loss: 26,
				},
				division: {
					name: 'central',
					rank: 4,
					win: 4,
					loss: 8,
					GamesBehind: 24.0,
				},
				winPercentage: 0.306,
			},
		],
	},
	{
		teamId: '8',
		allStar: '0',
		city: 'Dallas',
		fullName: 'Dallas Mavericks',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/b/b8/Mavericks_de_Dallas_logo.svg/150px-Mavericks_de_Dallas_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Mavericks',
		shortName: 'DAL',
		standings: [
			{
				win: 17,
				loss: 18,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 7,
					win: 14,
					loss: 10,
				},
				division: {
					name: 'southwest',
					rank: 2,
					win: 7,
					loss: 2,
					GamesBehind: 5.0,
				},
				winPercentage: 0.486,
			},
			{
				win: 42,
				loss: 30,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 5,
					win: 21,
					loss: 21,
				},
				division: {
					name: 'southwest',
					rank: 1,
					win: 7,
					loss: 5,
					GamesBehind: 0.0,
				},
				winPercentage: 0.583,
			},
		],
	},
	{
		teamId: '9',
		allStar: '0',
		city: 'Denver',
		fullName: 'Denver Nuggets',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/3/35/Nuggets_de_Denver_2018.png/180px-Nuggets_de_Denver_2018.png',
		nbaFranchise: '1',
		nickname: 'Nuggets',
		shortName: 'DEN',
		standings: [
			{
				win: 17,
				loss: 16,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 5,
					win: 10,
					loss: 9,
				},
				division: {
					name: 'northwest',
					rank: 2,
					win: 2,
					loss: 4,
					GamesBehind: 8.0,
				},
				winPercentage: 0.515,
			},
			{
				win: 47,
				loss: 25,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 3,
					win: 26,
					loss: 16,
				},
				division: {
					name: 'northwest',
					rank: 2,
					win: 9,
					loss: 3,
					GamesBehind: 5.0,
				},
				winPercentage: 0.653,
			},
		],
	},
	{
		teamId: '10',
		allStar: '0',
		city: 'Detroit',
		fullName: 'Detroit Pistons',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Detroit_Pistons_primary_logo_2017.png/150px-Detroit_Pistons_primary_logo_2017.png',
		nbaFranchise: '1',
		nickname: 'Pistons',
		shortName: 'DET',
		standings: [
			{
				win: 5,
				loss: 28,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 15,
					win: 4,
					loss: 17,
				},
				division: {
					name: 'central',
					rank: 5,
					win: 1,
					loss: 6,
					GamesBehind: 18.0,
				},
				winPercentage: 0.152,
			},
			{
				win: 20,
				loss: 52,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 15,
					win: 12,
					loss: 30,
				},
				division: {
					name: 'central',
					rank: 5,
					win: 1,
					loss: 11,
					GamesBehind: 26.0,
				},
				winPercentage: 0.278,
			},
		],
	},
	{
		teamId: '11',
		allStar: '0',
		city: 'Golden State',
		fullName: 'Golden State Warriors',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/d/de/Warriors_de_Golden_State_logo.svg/1200px-Warriors_de_Golden_State_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Warriors',
		shortName: 'GSW',
		standings: [
			{
				win: 27,
				loss: 7,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 1,
					win: 15,
					loss: 4,
				},
				division: {
					name: 'pacific',
					rank: 1,
					win: 7,
					loss: 1,
					GamesBehind: 0.0,
				},
				winPercentage: 0.794,
			},
			{
				win: 39,
				loss: 33,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 9,
					win: 25,
					loss: 17,
				},
				division: {
					name: 'pacific',
					rank: 4,
					win: 5,
					loss: 7,
					GamesBehind: 12.0,
				},
				winPercentage: 0.542,
			},
		],
	},
	{
		teamId: '14',
		allStar: '0',
		city: 'Houston',
		fullName: 'Houston Rockets',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/d/de/Houston_Rockets_logo_2003.png/330px-Houston_Rockets_logo_2003.png',
		nbaFranchise: '1',
		nickname: 'Rockets',
		shortName: 'HOU',
		standings: [
			{
				win: 10,
				loss: 26,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 15,
					win: 4,
					loss: 14,
				},
				division: {
					name: 'southwest',
					rank: 5,
					win: 1,
					loss: 3,
					GamesBehind: 12.5,
				},
				winPercentage: 0.278,
			},
			{
				win: 17,
				loss: 55,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 15,
					win: 11,
					loss: 31,
				},
				division: {
					name: 'southwest',
					rank: 5,
					win: 5,
					loss: 7,
					GamesBehind: 25.0,
				},
				winPercentage: 0.236,
			},
		],
	},
	{
		teamId: '15',
		allStar: '0',
		city: 'Indiana',
		fullName: 'Indiana Pacers',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/c/cf/Pacers_de_l%27Indiana_logo.svg/1180px-Pacers_de_l%27Indiana_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Pacers',
		shortName: 'IND',
		standings: [
			{
				win: 14,
				loss: 22,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 13,
					win: 8,
					loss: 17,
				},
				division: {
					name: 'central',
					rank: 4,
					win: 2,
					loss: 6,
					GamesBehind: 10.5,
				},
				winPercentage: 0.389,
			},
			{
				win: 34,
				loss: 38,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 9,
					win: 20,
					loss: 22,
				},
				division: {
					name: 'atlantic',
					rank: 2,
					win: 7,
					loss: 5,
					GamesBehind: 12.0,
				},
				winPercentage: 0.472,
			},
		],
	},
	{
		teamId: '16',
		allStar: '0',
		city: 'LA',
		fullName: 'LA Clippers',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/d/d6/Los_Angeles_Clippers_logo_2010.png',
		nbaFranchise: '1',
		nickname: 'Clippers',
		shortName: 'LAC',
		standings: [
			{
				win: 18,
				loss: 18,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 6,
					win: 12,
					loss: 14,
				},
				division: {
					name: 'southwest',
					rank: 3,
					win: 3,
					loss: 4,
					GamesBehind: 10.0,
				},
				winPercentage: 0.5,
			},
			{
				win: 47,
				loss: 25,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 4,
					win: 27,
					loss: 15,
				},
				division: {
					name: 'pacific',
					rank: 2,
					win: 9,
					loss: 3,
					GamesBehind: 4.0,
				},
				winPercentage: 0.653,
			},
		],
	},
	{
		teamId: '17',
		allStar: '0',
		city: 'Los Angeles',
		fullName: 'Los Angeles Lakers',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Los_Angeles_Lakers_logo.svg/220px-Los_Angeles_Lakers_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Lakers',
		shortName: 'LAL',
		standings: [
			{
				win: 17,
				loss: 19,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 8,
					win: 9,
					loss: 13,
				},
				division: {
					name: 'pacific',
					rank: 4,
					win: 1,
					loss: 5,
					GamesBehind: 11.0,
				},
				winPercentage: 0.472,
			},
			{
				win: 42,
				loss: 30,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 7,
					win: 25,
					loss: 17,
				},
				division: {
					name: 'pacific',
					rank: 3,
					win: 4,
					loss: 8,
					GamesBehind: 9.0,
				},
				winPercentage: 0.583,
			},
		],
	},
	{
		teamId: '19',
		allStar: '0',
		city: 'Memphis',
		fullName: 'Memphis Grizzlies',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/f/f1/Memphis_Grizzlies.svg/1200px-Memphis_Grizzlies.svg.png',
		nbaFranchise: '1',
		nickname: 'Grizzlies',
		shortName: 'MEM',
		standings: [
			{
				win: 23,
				loss: 14,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 4,
					win: 19,
					loss: 9,
				},
				division: {
					name: 'southwest',
					rank: 1,
					win: 4,
					loss: 2,
					GamesBehind: 0.0,
				},
				winPercentage: 0.622,
			},
			{
				win: 38,
				loss: 34,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 8,
					win: 19,
					loss: 23,
				},
				division: {
					name: 'southwest',
					rank: 2,
					win: 6,
					loss: 6,
					GamesBehind: 4.0,
				},
				winPercentage: 0.528,
			},
		],
	},
	{
		teamId: '20',
		allStar: '0',
		city: 'Miami',
		fullName: 'Miami Heat',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/1/1c/Miami_Heat_-_Logo.svg/1200px-Miami_Heat_-_Logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Heat',
		shortName: 'MIA',
		standings: [
			{
				win: 23,
				loss: 13,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 4,
					win: 16,
					loss: 7,
				},
				division: {
					name: 'southeast',
					rank: 1,
					win: 6,
					loss: 1,
					GamesBehind: 0.0,
				},
				winPercentage: 0.639,
			},
			{
				win: 20,
				loss: 32,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 6,
					win: 24,
					loss: 18,
				},
				division: {
					name: 'southeast',
					rank: 2,
					win: 6,
					loss: 6,
					GamesBehind: 12.5,
				},
				winPercentage: 0.278,
			},
		],
	},
	{
		teamId: '21',
		allStar: '0',
		city: 'Milwaukee',
		fullName: 'Milwaukee Bucks',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/3/34/Bucks2015.png',
		nbaFranchise: '1',
		nickname: 'Bucks',
		shortName: 'MIL',
		standings: [
			{
				win: 24,
				loss: 13,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 3,
					win: 17,
					loss: 9,
				},
				division: {
					name: 'central',
					rank: 2,
					win: 6,
					loss: 1,
					GamesBehind: 1.0,
				},
				winPercentage: 0.649,
			},
			{
				win: 46,
				loss: 26,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 3,
					win: 30,
					loss: 12,
				},
				division: {
					name: 'central',
					rank: 1,
					win: 11,
					loss: 1,
					GamesBehind: 0.0,
				},
				winPercentage: 0.639,
			},
		],
	},
	{
		teamId: '22',
		allStar: '0',
		city: 'Minnesota',
		fullName: 'Minnesota Timberwolves',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/d/d9/Timberwolves_du_Minnesota_logo_2017.png/200px-Timberwolves_du_Minnesota_logo_2017.png',
		nbaFranchise: '1',
		nickname: 'Timberwolves',
		shortName: 'MIN',
		standings: [
			{
				win: 16,
				loss: 19,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 9,
					win: 11,
					loss: 12,
				},
				division: {
					name: 'southwest',
					rank: 3,
					win: 2,
					loss: 4,
					GamesBehind: 10.5,
				},
				winPercentage: 0.457,
			},
			{
				win: 23,
				loss: 49,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 13,
					win: 15,
					loss: 27,
				},
				division: {
					name: 'northwest',
					rank: 4,
					win: 5,
					loss: 7,
					GamesBehind: 29.0,
				},
				winPercentage: 0.319,
			},
			{
				win: 19,
				loss: 45,
				seasonYear: 2019,
				conference: {
					name: 'west',
					rank: 14,
					win: 9,
					loss: 30,
				},
				division: {
					name: 'northwest',
					rank: 5,
					win: 2,
					loss: 10,
					GamesBehind: 22.5,
				},
				winPercentage: 0.297,
			},
		],
	},
	{
		teamId: '23',
		allStar: '0',
		city: 'New Orleans',
		fullName: 'New Orleans Pelicans',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/2/21/New_Orleans_Pelicans.png/200px-New_Orleans_Pelicans.png',
		nbaFranchise: '1',
		nickname: 'Pelicans',
		shortName: 'NOP',
		standings: [
			{
				win: 13,
				loss: 22,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 14,
					win: 8,
					loss: 14,
				},
				division: {
					name: 'southwest',
					rank: 4,
					win: 2,
					loss: 4,
					GamesBehind: 9.0,
				},
				winPercentage: 0.371,
			},
			{
				win: 31,
				loss: 41,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 11,
					win: 18,
					loss: 24,
				},
				division: {
					name: 'southwest',
					rank: 4,
					win: 6,
					loss: 6,
					GamesBehind: 11.0,
				},
				winPercentage: 0.431,
			},
		],
	},
	{
		teamId: '24',
		allStar: '0',
		city: 'New York',
		fullName: 'New York Knicks',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/d/dc/NY_Knicks_Logo_2011.png',
		nbaFranchise: '1',
		nickname: 'Knicks',
		shortName: 'NYK',
		standings: [
			{
				win: 17,
				loss: 19,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 10,
					win: 11,
					loss: 15,
				},
				division: {
					name: 'atlantic',
					rank: 4,
					win: 3,
					loss: 4,
					GamesBehind: 7.5,
				},
				winPercentage: 0.472,
			},
			{
				win: 41,
				loss: 31,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 4,
					win: 25,
					loss: 17,
				},
				division: {
					name: 'atlantic',
					rank: 3,
					win: 4,
					loss: 8,
					GamesBehind: 8.0,
				},
				winPercentage: 0.569,
			},
		],
	},
	{
		teamId: '25',
		allStar: '0',
		city: 'Oklahoma City',
		fullName: 'Oklahoma City Thunder',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/4/4f/Thunder_d%27Oklahoma_City_logo.svg/1200px-Thunder_d%27Oklahoma_City_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Thunder',
		shortName: 'OKC',
		standings: [
			{
				win: 13,
				loss: 22,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 12,
					win: 10,
					loss: 15,
				},
				division: {
					name: 'southwest',
					rank: 5,
					win: 1,
					loss: 2,
					GamesBehind: 13.0,
				},
				winPercentage: 0.371,
			},
			{
				win: 22,
				loss: 50,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 14,
					win: 12,
					loss: 30,
				},
				division: {
					name: 'northwest',
					rank: 5,
					win: 3,
					loss: 9,
					GamesBehind: 30.0,
				},
				winPercentage: 0.306,
			},
		],
	},
	{
		teamId: '26',
		allStar: '0',
		city: 'Orlando',
		fullName: 'Orlando Magic',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/b/bd/Orlando_Magic_logo_2010.png',
		nbaFranchise: '1',
		nickname: 'Magic',
		shortName: 'ORL',
		standings: [
			{
				win: 7,
				loss: 29,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 14,
					win: 4,
					loss: 21,
				},
				division: {
					name: 'southeast',
					rank: 5,
					win: 1,
					loss: 8,
					GamesBehind: 16.0,
				},
				winPercentage: 0.194,
			},
			{
				win: 21,
				loss: 51,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 14,
					win: 13,
					loss: 29,
				},
				division: {
					name: 'southeast',
					rank: 5,
					win: 4,
					loss: 8,
					GamesBehind: 20.0,
				},
				winPercentage: 0.292,
			},
		],
	},
	{
		teamId: '27',
		allStar: '0',
		city: 'Philadelphia',
		fullName: 'Philadelphia 76ers',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/4/48/76ers_2016.png',
		nbaFranchise: '1',
		nickname: '76ers',
		shortName: 'PHI',
		standings: [
			{
				win: 19,
				loss: 16,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 6,
					win: 13,
					loss: 10,
				},
				division: {
					name: 'atlantic',
					rank: 2,
					win: 3,
					loss: 6,
					GamesBehind: 5.0,
				},
				winPercentage: 0.543,
			},
			{
				win: 49,
				loss: 23,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 1,
					win: 31,
					loss: 11,
				},
				division: {
					name: 'atlantic',
					rank: 1,
					win: 10,
					loss: 2,
					GamesBehind: 0.0,
				},
				winPercentage: 0.681,
			},
		],
	},
	{
		teamId: '28',
		allStar: '0',
		city: 'Phoenix',
		fullName: 'Phoenix Suns',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/5/56/Phoenix_Suns_2013.png',
		nbaFranchise: '1',
		nickname: 'Suns',
		shortName: 'PHX',
		standings: [
			{
				win: 27,
				loss: 8,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 2,
					win: 18,
					loss: 7,
				},
				division: {
					name: 'southwest',
					rank: 2,
					win: 4,
					loss: 4,
					GamesBehind: 0.5,
				},
				winPercentage: 0.771,
			},
			{
				win: 51,
				loss: 21,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 2,
					win: 30,
					loss: 12,
				},
				division: {
					name: 'pacific',
					rank: 1,
					win: 7,
					loss: 5,
					GamesBehind: 0.0,
				},
				winPercentage: 0.708,
			},
		],
	},
	{
		teamId: '29',
		allStar: '0',
		city: 'Portland',
		fullName: 'Portland Trail Blazers',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/en/thumb/2/21/Portland_Trail_Blazers_logo.svg/1200px-Portland_Trail_Blazers_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Trail Blazers',
		shortName: 'POR',
		standings: [
			{
				win: 13,
				loss: 21,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 12,
					win: 7,
					loss: 17,
				},
				division: {
					name: 'northwest',
					rank: 4,
					win: 1,
					loss: 4,
					GamesBehind: 12.5,
				},
				winPercentage: 0.382,
			},
			{
				win: 42,
				loss: 30,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 6,
					win: 23,
					loss: 19,
				},
				division: {
					name: 'northwest',
					rank: 3,
					win: 6,
					loss: 6,
					GamesBehind: 10.0,
				},
				winPercentage: 0.583,
			},
			{
				win: 19,
				loss: 45,
				seasonYear: 2019,
				conference: {
					name: 'west',
					rank: 14,
					win: 9,
					loss: 30,
				},
				division: {
					name: 'northwest',
					rank: 5,
					win: 2,
					loss: 10,
					GamesBehind: 22.5,
				},
				winPercentage: 0.297,
			},
			{
				win: 53,
				loss: 29,
				seasonYear: 2018,
				conference: {
					name: 'west',
					rank: 3,
					win: 29,
					loss: 23,
				},
				division: {
					name: 'northwest',
					rank: 2,
					win: 6,
					loss: 10,
					GamesBehind: 1.0,
				},
				winPercentage: 0.646,
			},
		],
	},
	{
		teamId: '30',
		allStar: '0',
		city: 'Sacramento',
		fullName: 'Sacramento Kings',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/thumb/9/95/Kings_de_Sacramento_logo.svg/1200px-Kings_de_Sacramento_logo.svg.png',
		nbaFranchise: '1',
		nickname: 'Kings',
		shortName: 'SAC',
		standings: [
			{
				win: 15,
				loss: 22,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 11,
					win: 11,
					loss: 16,
				},
				division: {
					name: 'pacific',
					rank: 5,
					win: 4,
					loss: 5,
					GamesBehind: 13.5,
				},
				winPercentage: 0.405,
			},
			{
				win: 31,
				loss: 41,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 12,
					win: 18,
					loss: 24,
				},
				division: {
					name: 'pacific',
					rank: 5,
					win: 5,
					loss: 7,
					GamesBehind: 20.0,
				},
				winPercentage: 0.431,
			},
		],
	},
	{
		allStar: '0',
		city: 'San Antonio',
		fullName: 'San Antonio Spurs',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/0/0e/San_Antonio_Spurs_2018.png',
		nbaFranchise: '1',
		nickname: 'Spurs',
		shortName: 'SAS',
		teamId: '31',
		standings: [
			{
				win: 14,
				loss: 20,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 10,
					win: 8,
					loss: 15,
				},
				division: {
					name: 'southwest',
					rank: 3,
					win: 1,
					loss: 4,
					GamesBehind: 7.5,
				},
				winPercentage: 0.412,
			},
			{
				win: 33,
				loss: 39,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 10,
					win: 17,
					loss: 25,
				},
				division: {
					name: 'southwest',
					rank: 3,
					win: 6,
					loss: 6,
					GamesBehind: 9.0,
				},
				winPercentage: 0.458,
			},
		],
	},
	{
		allStar: '0',
		city: 'Toronto',
		fullName: 'Toronto Raptors',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/8/89/Raptors2015.png',
		nbaFranchise: '1',
		nickname: 'Raptors',
		shortName: 'TOR',
		teamId: '38',
		standings: [
			{
				win: 15,
				loss: 17,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 11,
					win: 10,
					loss: 11,
				},
				division: {
					name: 'atlantic',
					rank: 5,
					win: 4,
					loss: 5,
					GamesBehind: 7.5,
				},
				winPercentage: 0.469,
			},
			{
				win: 27,
				loss: 45,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 12,
					win: 17,
					loss: 25,
				},
				division: {
					name: 'atlantic',
					rank: 5,
					win: 4,
					loss: 8,
					GamesBehind: 22.0,
				},
				winPercentage: 0.375,
			},
		],
	},
	{
		allStar: '0',
		city: 'Utah',
		fullName: 'Utah Jazz',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/3/3b/Jazz_de_l%27Utah_logo.png',
		nbaFranchise: '1',
		nickname: 'Jazz',
		shortName: 'UTA',
		teamId: '40',
		standings: [
			{
				win: 27,
				loss: 9,
				seasonYear: 2021,
				conference: {
					name: 'west',
					rank: 3,
					win: 16,
					loss: 3,
				},
				division: {
					name: 'northwest',
					rank: 1,
					win: 8,
					loss: 0,
					GamesBehind: 0.0,
				},
				winPercentage: 0.743,
			},
			{
				win: 52,
				loss: 20,
				seasonYear: 2020,
				conference: {
					name: 'west',
					rank: 1,
					win: 28,
					loss: 14,
				},
				division: {
					name: 'northwest',
					rank: 1,
					win: 7,
					loss: 5,
					GamesBehind: 0.0,
				},
				winPercentage: 0.722,
			},
		],
	},
	{
		allStar: '0',
		city: 'Washington',
		fullName: 'Washington Wizards',
		leagues: 'standard',
		logo: 'https://upload.wikimedia.org/wikipedia/fr/archive/d/d6/20161212034849%21Wizards2015.png',
		nbaFranchise: '1',
		nickname: 'Wizards',
		shortName: 'WAS',
		teamId: '41',
		standings: [
			{
				win: 18,
				loss: 17,
				seasonYear: 2021,
				conference: {
					name: 'east',
					rank: 8,
					win: 12,
					loss: 11,
				},
				division: {
					name: 'southeast',
					rank: 3,
					win: 3,
					loss: 5,
					GamesBehind: 4.5,
				},
				winPercentage: 0.514,
			},
			{
				win: 34,
				loss: 38,
				seasonYear: 2020,
				conference: {
					name: 'east',
					rank: 8,
					win: 16,
					loss: 26,
				},
				division: {
					name: 'southeast',
					rank: 3,
					win: 3,
					loss: 9,
					GamesBehind: 7.0,
				},
				winPercentage: 0.472,
			},
		],
	},
];

// const [teamName, setTeamName] = useState('');
// const [teamAbb, setTeamAbb] = useState('');
// const [logo, setLogo] = useState('');
// const [city, setCity] = useState('');
// const [id, setId] = useState(0);
// useEffect(() => {
// 	const url = fetch(
// 		'https://api-nba-v1.p.rapidapi.com/teams/league/standard',
// 		{
// 			method: 'GET',
// 			headers: {
// 				'x-rapidapi-host': 'api-nba-v1.p.rapidapi.com',
// 				'x-rapidapi-key':
// 					'04ae5e1002msh74ff5480ca1af46p132c28jsn451192ec026b',
// 			},
// 		}
// 	);

// 	const fetchData = async () => {
// 		try {
// 			const res = await url;
// 			const json = await res.json();
// 			const teamData = json.api.teams;
// 			setTeamName(
// 				teamData.map((data) => {
// 					return data.fullName[0];
// 				})
// 			);
// 			setTeamAbb(
// 				teamData.map((data) => {
// 					return data.shortName[0];
// 				})
// 			);
// 			setLogo(
// 				teamData.map((data) => {
// 					return data.logo[0];
// 				})
// 			);
// 			setCity(
// 				teamData.map((data) => {
// 					return data.city[0];
// 				})
// 			);
// 			setId(
// 				teamData.map((data) => {
// 					return data.teamId[0];
// 				})
// 			);
// 		} catch (error) {
// 			console.log('error', error);
// 		}
// 	};
// 	fetchData();
// }, []);

// return (
// 	<NbaTeamsDataApi
// 		value={{ teamAbb, teamName, id, city, logo }}/>
// );
